objects/DynamicQueryHelper__c/DynamicQueryHelper__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>DynamicQueryHelper</label>
</CustomObject>

objects/DynamicQueryHelper__c/fields/Active_Products_Condition__c.field-meta.xml
<CustomField>
    <fullName>Active_Products_Condition__c</fullName>
    <label>Active Products Condition</label>
    <type>TextArea</type>
</CustomField>

objects/DynamicQueryHelper__c/fields/ServiceContact_Query__c.field-meta.xml
<CustomField>
    <fullName>ServiceContact_Query__c</fullName>
    <label>ServiceContact Query</label>
    <type>TextArea</type>
</CustomField>

objects/DynamicQueryHelper__c/fields/Without_Active_Product_Condition__c.field-meta.xml
<CustomField>
    <fullName>Without_Active_Product_Condition__c</fullName>
    <label>Without Active Product Condition</label>
    <type>TextArea</type>
</CustomField>

classes/Utilities.cls
/*******************************************************************************************
* @Name         Utilities 
* @Author       Manjunath Vittal Rao
* @Date         03/07/2021
* @Group        Utilities
* @Description  This class is used as a support class for all the apex in this Org.
*******************************************************************************************/
/* MODIFICATION LOG
* Version          Developer                    Date               Description
*-------------------------------------------------------------------------------------------
*  1.0            Manjunath Vittal Rao       03/07/2021              Initial Creation                                                      
*******************************************************************************************/
public class Utilities {
    public static list<ServiceContract> getSerContractProdDetails(boolean isActiveReq, String extenId){
        String queryString = '';
        DynamicQueryHelper__c queryStrCS = DynamicQueryHelper__c.getOrgDefaults();
        queryString = queryStrCS.ServiceContact_Query__c;
        queryString += ' where '+queryStrCS.Without_Active_Product_Condition__c+' extenId';
        if(isActiveReq){
            queryString += ' and '+queryStrCS.Active_Products_Condition__c;
        }
        system.debug('extenId - '+extenId);
        system.debug('Query - '+queryString);
        return Database.query(queryString);
    }
}